name: Gleam CI

on:
  push:
    paths:
      - "gleam_md5/**"
      - ".github/workflows/gleam.yml"
  pull_request:
    paths:
      - "gleam_md5/**"

jobs:
  gleam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '27'
          gleam-version: '1.11.0'

      - name: Run Gleam tests
        working-directory: gleam_md5
        run: gleam test